server:
  port: 8081
#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.tiptimes.*.entity

#分页插件
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true

#mysql配置
spring:
  datasource:
    # 本地
    url: jdbc:mysql://localhost:3306/identity?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #线上
#    url: jdbc:mysql://121.36.175.7:3088/identity?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: tiptimes@2013
#    url: jdbc:mysql://localhost:3088/identity?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: tiptimes@2013
    hikari:
      idle-timeout: 600000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 1800000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 121.36.175.7
    port: 6379
    password: 20130909
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 30000

logging:
  level:
    com:
      tiptimes:
        identity:
          dao: debug
#fastDFS
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 150
    height: 150
  tracker-list: 121.36.175.7:22122
  resHost: http://121.36.175.7
  storagePort: 80
#文件存储路径
file-save-path: /data/identity/
#file-save-path: E:/data/identity/

# Swagger json url address
swagger.url: https://petstore.swagger.io/v2/swagger.json